### ISSUE TITLE
EE-880: Duplicate Invoice Validation: The validation must consider the full invoice date, not just the year.

### ISSUE THREAD

**Issue by juanfunes1996** [etendosoftware/com.etendoerp.procurement.extensions#1]
# Error's description
The current validation to detect a duplicate invoice at the time of saving the header is to check the third party, reference, and the year of the invoice date field.

This last point should be modified, and it shouldn't just look at the year but compare the entire invoice date.

 # Steps to reproduce the error
 ### Required Configurations (if necessary)
1- Enable "Validate duplicate purchase invoices" preference.
![image](https://github.com/etendosoftware/com.etendoerp.procurement.extensions/assets/143511686/a77c7504-4309-488c-a2b7-8987bdc88df6)
2 - Create an invoice with the same third party, reference and year as another existing invoice.
![image](https://github.com/etendosoftware/com.etendoerp.procurement.extensions/assets/143511686/9e464eb3-e13a-45e8-99c6-ecc4c5d9e206)
3 - When trying to save the header the error will be displayed.
![image](https://github.com/etendosoftware/com.etendoerp.procurement.extensions/assets/143511686/ef7f22ca-8145-489a-a8cf-5efc18076b5b)

 # Expected behavior
The validation should not only look at the year but compare the whole invoice date.

 # Affected Version
 ¿Latest/Specific?
 Version number:
Core: 23.4.5
com.etendoerp.procurement.extensions:  1.0.0

 # Solution Design (optional)

 # Other test cases
 **Given:**
 **When:**
 **Then:**

**Comment by valeg-etendo** [comment]
> [!IMPORTANT]
> Bug resolved in version [1.1.1](https://github.com/etendosoftware/com.etendoerp.procurement.extensions/releases/tag/1.1.1).
