### ISSUE TITLE
EE-949: Error in the compilation of trigger PIV_PREVENT_DUPLICATED_INV_TRG with Oracle as database.

### ISSUE THREAD

**Issue by juanfunes1996** [etendosoftware/com.etendoerp.procurement.extensions#2]
# Error's description
When compiling all triggers in an environment with oracle as database, the following triggers are failing to compile:

Trigger: PIV_PREVENT_DUPLICATED_INV_TRG (Module: com.etendoerp.purchase.invoice.validations)
![image](https://github.com/etendosoftware/com.etendoerp.procurement.extensions/assets/143511686/4d7c5f6c-c17d-42d8-9165-42b9ae8522d0)

 # Steps to reproduce the error
 ### Required Configurations (if necessary)

Download the modules mentioned above.
Open SQL Developer with the oracle database.
Compile the triggers.

 # Expected behavior
All triggers should compile without errors.

 # Affected Version
 ¿Latest/Specific?
 Version number:
Etendo Core: 24.1.2
Module: com.etendoerp.purchase.invoice.validations

 # Solution Design (optional)

 # Other test cases
 Given: An etendo core with the bundles procurement, platform and sales extensions installed and Oracle as database.
 When: Compile the triggers.
 Then: All triggers should compile without errors.

**Comment by valeg-etendo** [comment]
> [!IMPORTANT]
> Bug resolved in version [1.1.2](https://github.com/etendosoftware/com.etendoerp.procurement.extensions/releases/tag/1.1.2).
